#include <stdio.h>
#include <util.h>
#include <utee_defines.h>

#include <ca_bsw_csm.h>

#include "test_bsw_csm_data.h"
#include <nist/186-2ecdsatestvectors.h>

#define ARRAY(a)            a, ARRAY_SIZE(a)
#define NULL_ARRAY(a)       NULL, 0

struct test_ac_case {
	uint32_t algo;
	TEE_OperationMode mode;

	union {
		struct {
			const uint8_t *modulus;
			size_t modulus_len;

			const uint8_t *pub_exp;
			size_t pub_exp_len;

			const uint8_t *priv_exp;
			size_t priv_exp_len;

			const uint8_t *prime1;  /* q */
			size_t prime1_len;
			const uint8_t *prime2;  /* p */
			size_t prime2_len;
			const uint8_t *exp1;    /* dp */
			size_t exp1_len;
			const uint8_t *exp2;    /* dq */
			size_t exp2_len;
			const uint8_t *coeff;   /* iq */
			size_t coeff_len;

			int salt_len;
		} rsa;
		struct {
			const uint8_t *prime;
			size_t prime_len;
			const uint8_t *sub_prime;
			size_t sub_prime_len;
			const uint8_t *base;
			size_t base_len;
			const uint8_t *pub_val;
			size_t pub_val_len;
			const uint8_t *priv_val;
			size_t priv_val_len;
		} dsa;
		struct {
			const uint8_t *private;
			size_t private_len;
			const uint8_t *public_x;
			size_t public_x_len;
			const uint8_t *public_y;
			size_t public_y_len;
		} ecdsa;
	} params;

	const uint8_t *ptx;
	size_t ptx_len;
	const uint8_t *ctx;
	size_t ctx_len;
	size_t line;
};

#define WITHOUT_SALT(x) -1
#define WITH_SALT(x)    x

#define TEST_AC_CASE(algo, mode, vect, union_params) \
	{ (algo), (mode), .params = union_params, \
	  ARRAY(vect ## _ptx), \
	  ARRAY(vect ## _out), \
	  __LINE__ }

#define TEST_AC_RSA_UNION(vect, opt_crt_array, opt_salt) \
	{ .rsa = { \
		  ARRAY(vect ## _modulus), \
		  ARRAY(vect ## _pub_exp), \
		  ARRAY(vect ## _priv_exp), \
		  opt_crt_array(vect ## _prime1), \
		  opt_crt_array(vect ## _prime2), \
		  opt_crt_array(vect ## _exp1), \
		  opt_crt_array(vect ## _exp2), \
		  opt_crt_array(vect ## _coeff), \
		  opt_salt(vect ## _salt_len) \
	  } }

#define TEST_AC_RSA_CASE(algo, mode, vect, opt_crt_array, opt_salt) \
	TEST_AC_CASE(algo, mode, vect, \
		      TEST_AC_RSA_UNION(vect, opt_crt_array, opt_salt))

#define TEST_AC_DSA_UNION(vect) \
	{ .dsa = { \
		  ARRAY(vect ## _prime), \
		  ARRAY(vect ## _sub_prime), \
		  ARRAY(vect ## _base), \
		  ARRAY(vect ## _pub_val), \
		  ARRAY(vect ## _priv_val), \
	  } }

#define TEST_AC_DSA_CASE(algo, mode, vect) \
	TEST_AC_CASE(algo, mode, vect, TEST_AC_DSA_UNION(vect))

#define TEST_AC_ECDSA_UNION(vect) \
	{ .ecdsa = { \
		  ARRAY(vect ## _private), \
		  ARRAY(vect ## _public_x), \
		  ARRAY(vect ## _public_y), \
	  } }

#define TEST_AC_ECDSA_CASE(algo, mode, vect) \
	TEST_AC_CASE(algo, mode, vect, TEST_AC_ECDSA_UNION(vect))

static const struct test_ac_case test_ac_cases[] = {
	/* RSA test without crt parameters */
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect18, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect18, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect19, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect19, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect3, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect3, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect4, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect4, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect5, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect5, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect6, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect6, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect7, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect7, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect8, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect8, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA224, TEE_MODE_SIGN,
			  ac_rsassa_vect16, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA224, TEE_MODE_VERIFY,
			  ac_rsassa_vect16, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA256, TEE_MODE_SIGN,
			  ac_rsassa_vect9, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA256, TEE_MODE_VERIFY,
			  ac_rsassa_vect9, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA384, TEE_MODE_SIGN,
			  ac_rsassa_vect10, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA384, TEE_MODE_VERIFY,
			  ac_rsassa_vect10, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA512, TEE_MODE_SIGN,
			  ac_rsassa_vect11, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA512, TEE_MODE_VERIFY,
			  ac_rsassa_vect11, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA1,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect12, NULL_ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect12, NULL_ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA224,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect17, NULL_ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA224,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect17, NULL_ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect13, NULL_ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect13, NULL_ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA384,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect14, NULL_ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA384,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect14, NULL_ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA512,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect15, NULL_ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA512,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect15, NULL_ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect15, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect15, NULL_ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect1, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect2, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect10, NULL_ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect10, NULL_ARRAY, WITHOUT_SALT),

	/* RSA test with crt parameters */
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_ENCRYPT,
			  ac_rsassa_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSA_NOPAD, TEE_MODE_DECRYPT,
			  ac_rsassa_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect3, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect3, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect4, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect4, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect5, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect5, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect6, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect6, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect7, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect7, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect8, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY,
			  ac_rsassa_vect8, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA256, TEE_MODE_SIGN,
			  ac_rsassa_vect9, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA256, TEE_MODE_VERIFY,
			  ac_rsassa_vect9, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA384, TEE_MODE_SIGN,
			  ac_rsassa_vect10, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA384, TEE_MODE_VERIFY,
			  ac_rsassa_vect10, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA512, TEE_MODE_SIGN,
			  ac_rsassa_vect11, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_V1_5_SHA512, TEE_MODE_VERIFY,
			  ac_rsassa_vect11, ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA1,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect12, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA1, TEE_MODE_SIGN,
			  ac_rsassa_vect12, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA224,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect17, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA224,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect17, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect13, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect13, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA384,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect14, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA384,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect14, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA512,
			  TEE_MODE_VERIFY,
			  ac_rsassa_vect15, ARRAY, WITH_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA512,
			  TEE_MODE_SIGN,
			  ac_rsassa_vect15, ARRAY, WITH_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_DECRYPT,
			  ac_rsaes_pkcs1_v1_5_vect15, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_V1_5, TEE_MODE_ENCRYPT,
			  ac_rsaes_pkcs1_v1_5_vect15, ARRAY, WITHOUT_SALT),

	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect1, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect2, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_DECRYPT,
			  ac_rsaes_oaep_vect10, ARRAY, WITHOUT_SALT),
	TEST_AC_RSA_CASE(TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA1,
			  TEE_MODE_ENCRYPT,
			  ac_rsaes_oaep_vect10, ARRAY, WITHOUT_SALT),

	/* DSA tests */
	/* [mod = L=1024, N=160, SHA-1] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect1),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect1),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect2),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect2),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect3),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect3),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect4),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect4),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect5),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect5),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect6),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect6),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect7),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect7),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect8),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect8),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect9),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect9),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect10),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect10),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect11),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect11),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect12),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect12),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect13),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect13),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect14),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect14),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_VERIFY, ac_dsa_vect15),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA1, TEE_MODE_SIGN, ac_dsa_vect15),
	/* [mod = L=1024, N=160, SHA-224] - GP NOT SUPPORTED */
	/* [mod = L=1024, N=160, SHA-256] - GP NOT SUPPORTED */
	/* [mod = L=1024, N=160, SHA-384] - GP NOT SUPPORTED */
	/* [mod = L=1024, N=160, SHA-512] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=224, SHA-1] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=224, SHA-224] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect91),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect91),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect92),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect92),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect93),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect93),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect94),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect94),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect95),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect95),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect96),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect96),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect97),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect97),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect98),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect98),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect99),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect99),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect100),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect100),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect101),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect101),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect102),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect102),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect103),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect103),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect104),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect104),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect105),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect105),
	/* [mod = L=2048, N=224, SHA-256] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect106),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect106),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect107),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect107),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect108),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect108),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect109),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect109),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect110),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect110),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect111),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect111),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect112),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect112),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect113),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect113),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect114),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect114),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect115),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect115),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect116),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect116),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect117),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect117),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect118),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect118),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect119),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect119),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect120),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect120),
	/* [mod = L=2048, N=224, SHA-384] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=224, SHA-512] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=256, SHA-1] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=256, SHA-224] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect166),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect166),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect167),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect167),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect168),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect168),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect169),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect169),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect170),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect170),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect171),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect171),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect172),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect172),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect173),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect173),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect174),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect174),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect175),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect175),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect176),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect176),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect177),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect177),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect178),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect178),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect179),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect179),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_VERIFY, ac_dsa_vect180),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA224, TEE_MODE_SIGN, ac_dsa_vect180),
	/* [mod = L=2048, N=256, SHA-256] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect181),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect181),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect182),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect182),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect183),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect183),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect184),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect184),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect185),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect185),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect186),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect186),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect187),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect187),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect188),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect188),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect189),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect189),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect190),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect190),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect191),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect191),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect192),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect192),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect193),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect193),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect194),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect194),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect195),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect195),
	/* [mod = L=2048, N=256, SHA-384] - GP NOT SUPPORTED */
	/* [mod = L=2048, N=256, SHA-512] - GP NOT SUPPORTED */
	/* [mod = L=3072, N=256, SHA-1] - GP NOT SUPPORTED */
	/* [mod = L=3072, N=256, SHA-224] - GP NOT SUPPORTED */
	/* [mod = L=3072, N=256, SHA-256] */
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect256),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect256),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect257),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect257),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect258),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect258),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect259),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect259),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect260),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect260),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect261),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect261),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect262),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect262),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect263),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect263),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect264),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect264),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect265),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect265),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect266),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect266),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect267),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect267),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect268),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect268),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect269),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect269),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_VERIFY, ac_dsa_vect270),
	TEST_AC_DSA_CASE(TEE_ALG_DSA_SHA256, TEE_MODE_SIGN, ac_dsa_vect270),
	/* [mod = L=3072, N=256, SHA-384] - GP NOT SUPPORTED */
	/* [mod = L=3072, N=256, SHA-512] - GP NOT SUPPORTED */

	/* ECDSA tests */
	/* [P-192] */
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_1),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_1),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_2),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_2),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_3),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_3),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_4),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_4),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_5),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_5),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_6),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_6),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_7),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_7),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_8),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_8),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_9),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_9),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_10),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_10),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_11),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_11),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_12),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_12),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_13),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_13),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_14),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_14),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_15),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P192, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_15),
	/* [P-224] */
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_16),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_16),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_17),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_17),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_18),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_18),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_19),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_19),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_20),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_20),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_21),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_21),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_22),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_22),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_23),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_23),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_24),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_24),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_25),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_25),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_26),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_26),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_27),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_27),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_28),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_28),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_29),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_29),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_30),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P224, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_30),
	/* [P-256] */
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_31),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_31),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_32),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_32),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_33),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_33),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_34),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_34),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_35),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_35),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_36),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_36),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_37),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_37),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_38),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_38),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_39),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_39),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_40),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_40),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_41),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_41),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_42),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_42),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_43),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_43),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_44),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_44),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_45),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P256, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_45),
	/* [P-384] */
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_46),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_46),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_47),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_47),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_48),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_48),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_49),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_49),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_50),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_50),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_51),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_51),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_52),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_52),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_53),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_53),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_54),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_54),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_55),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_55),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_56),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_56),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_57),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_57),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_58),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_58),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_59),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_59),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_60),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P384, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_60),
	/* [P-521] */
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_61),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_61),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_62),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_62),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_63),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_63),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_64),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_64),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_65),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_65),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_66),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_66),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_67),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_67),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_68),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_68),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_69),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_69),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_70),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_70),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_71),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_71),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_72),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_72),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_73),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_73),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_74),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_74),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_VERIFY,
			    nist_186_2_ecdsa_testvector_75),
	TEST_AC_ECDSA_CASE(TEE_ALG_ECDSA_P521, TEE_MODE_SIGN,
			    nist_186_2_ecdsa_testvector_75),
	/* [K-163] - GP NOT SUPPORTED */
	/* [K-233] - GP NOT SUPPORTED */
	/* [K-283] - GP NOT SUPPORTED */
	/* [K-409] - GP NOT SUPPORTED */
	/* [K-571] - GP NOT SUPPORTED */
	/* [B-163] - GP NOT SUPPORTED */
	/* [B-233] - GP NOT SUPPORTED */
	/* [B-283] - GP NOT SUPPORTED */
	/* [B-409] - GP NOT SUPPORTED */
	/* [B-571] - GP NOT SUPPORTED */
};

static bool create_key(TEEC_Session *s,
		       uint32_t max_key_size, uint32_t key_type,
		       TEE_Attribute *attrs, size_t num_attrs,
		       TEE_ObjectHandle *obh)
{
	size_t n;
	TEEC_Result res;

	res = ta_crypt_cmd_allocate_transient_object(s, key_type,
			max_key_size, obh);
	if (res != TEEC_SUCCESS)
		return res;

	res = ta_crypt_cmd_populate_transient_object(s, *obh, attrs,
			num_attrs);
	if (res != TEEC_SUCCESS)
		return res;

	for (n = 0; n < num_attrs; n++) {
		uint8_t out[512];
		size_t out_size;

		out_size = sizeof(out);
		memset(out, 0, sizeof(out));

		if (attrs[n].attributeID == TEE_ATTR_ECC_CURVE)
			continue;

		res = ta_crypt_cmd_get_object_buffer_attribute(s, *obh,
				attrs[n].attributeID, out, &out_size);
		if (res != TEEC_SUCCESS)
			return res;

		if (out_size < attrs[n].content.ref.length) {
			memmove(out + (attrs[n].content.ref.length - out_size),
				out,
				attrs[n].content.ref.length);
			memset(out, 0, attrs[n].content.ref.length - out_size);
			out_size = attrs[n].content.ref.length;
		}

		//if (!ADBG_EXPECT_BUFFER(c, attrs[n].content.ref.buffer,
		//	attrs[n].content.ref.length, out, out_size))
		//	return false;
	}

	return true;
}

static TEEC_Result test_bsw_csm_asymmetric_cipher(struct ca_ctx *ctx)
{
	TEE_OperationHandle op = TEE_HANDLE_NULL;
	TEE_ObjectHandle obh1 = TEE_HANDLE_NULL;
	TEE_ObjectHandle obh2 = TEE_HANDLE_NULL;
	TEE_Attribute key_attrs[8];
	TEE_Attribute algo_params[1];
	size_t num_algo_params;
	uint8_t out[512];
	size_t out_size;
	uint8_t out_enc[512];
	size_t out_enc_size;
	uint8_t ptx_hash[TEE_MAX_HASH_SIZE];
	size_t ptx_hash_size;
	size_t max_key_size;
	size_t num_key_attrs;
	uint32_t ret_orig;
	size_t n;
	uint32_t curve;
	uint32_t hash_algo;
	TEEC_Result res;

	for (n = 0; n < ARRAY_SIZE(test_ac_cases); n++) {
		const struct test_ac_case *tv = test_ac_cases + n;

		printf("Asym Crypto case %d algo 0x%x line %d\n",
				     (int)n, (unsigned int)tv->algo,
				     (int)tv->line);

		/*
		 * When signing or verifying we're working with the hash of
		 * the payload.
		 */
		if (tv->mode == TEE_MODE_VERIFY || tv->mode == TEE_MODE_SIGN) {
			if (TEE_ALG_GET_MAIN_ALG(tv->algo) == TEE_MAIN_ALGO_ECDSA)
				hash_algo = TEE_ALG_SHA1;
			else
				hash_algo = TEE_ALG_HASH_ALGO(
					TEE_ALG_GET_DIGEST_HASH(tv->algo));

			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, hash_algo, TEE_MODE_DIGEST, 0);
			if (res != TEEC_SUCCESS)
				return res;

			ptx_hash_size = sizeof(ptx_hash);
			res = ta_crypt_cmd_digest_do_final(&ctx->sess, op,
					tv->ptx, tv->ptx_len, ptx_hash,
					&ptx_hash_size);
			if (res != TEEC_SUCCESS)
				return res;

			/*
			 * When we use DSA algorithms, the size of the hash we
			 * consider equals the min between the size of the
			 * "subprime" in the key and the size of the hash
			 */
			if (TEE_ALG_GET_MAIN_ALG(tv->algo) ==
			    TEE_MAIN_ALGO_DSA) {
				if (tv->params.dsa.sub_prime_len <=
				    ptx_hash_size)
					ptx_hash_size =
						tv->params.dsa.sub_prime_len;
			}

			res = ta_crypt_cmd_free_operation(&ctx->sess, op);
			if (res != TEEC_SUCCESS)
				return res;
		}

		num_algo_params = 0;
		num_key_attrs = 0;
		switch (TEE_ALG_GET_MAIN_ALG(tv->algo)) {
		case TEE_MAIN_ALGO_RSA:
			if (tv->params.rsa.salt_len > 0) {
				algo_params[0].attributeID =
					TEE_ATTR_RSA_PSS_SALT_LENGTH;
				algo_params[0].content.value.a =
					tv->params.rsa.salt_len;
				algo_params[0].content.value.b = 0;
				num_algo_params = 1;
			}

			max_key_size = tv->params.rsa.modulus_len * 8;

			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_RSA_MODULUS,
				       tv->params.rsa.modulus,
				       tv->params.rsa.modulus_len);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_RSA_PUBLIC_EXPONENT,
				       tv->params.rsa.pub_exp,
				       tv->params.rsa.pub_exp_len);

			if (!create_key(&ctx->sess,
					   max_key_size,
					   TEE_TYPE_RSA_PUBLIC_KEY,
					   key_attrs,
					   num_key_attrs,
					   &obh2))
				return false;

			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_RSA_PRIVATE_EXPONENT,
				       tv->params.rsa.priv_exp,
				       tv->params.rsa.priv_exp_len);

			if (tv->params.rsa.prime1_len != 0) {
				tee_add_attr(&num_key_attrs, key_attrs,
					       TEE_ATTR_RSA_PRIME1,
					       tv->params.rsa.prime1,
					       tv->params.rsa.prime1_len);
			}

			if (tv->params.rsa.prime2_len != 0) {
				tee_add_attr(&num_key_attrs, key_attrs,
			       TEE_ATTR_RSA_PRIME2,
			       tv->params.rsa.prime2,
			       tv->params.rsa.prime2_len);
			}

			if (tv->params.rsa.exp1_len != 0) {
				tee_add_attr(&num_key_attrs, key_attrs,
			       TEE_ATTR_RSA_EXPONENT1,
			       tv->params.rsa.exp1,
			       tv->params.rsa.exp1_len);
			}

			if (tv->params.rsa.exp2_len != 0) {
				tee_add_attr(&num_key_attrs, key_attrs,
			       TEE_ATTR_RSA_EXPONENT2,
			       tv->params.rsa.exp2,
			       tv->params.rsa.exp2_len);
			}

			if (tv->params.rsa.coeff_len != 0) {
				tee_add_attr(&num_key_attrs, key_attrs,
			       TEE_ATTR_RSA_COEFFICIENT,
			       tv->params.rsa.coeff,
			       tv->params.rsa.coeff_len);
			}

			if (!create_key(&ctx->sess,
				 max_key_size,
				 TEE_TYPE_RSA_KEYPAIR,
				 key_attrs,
				 num_key_attrs,
				 &obh1))
				return false;
			break;

		case TEE_MAIN_ALGO_DSA:
			max_key_size = tv->params.dsa.prime_len * 8;

			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_DSA_PRIME,
				       tv->params.dsa.prime,
				       tv->params.dsa.prime_len);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_DSA_SUBPRIME,
				       tv->params.dsa.sub_prime,
				       tv->params.dsa.sub_prime_len);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_DSA_BASE,
				       tv->params.dsa.base,
				       tv->params.dsa.base_len);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_DSA_PUBLIC_VALUE,
				       tv->params.dsa.pub_val,
				       tv->params.dsa.pub_val_len);

			if (!create_key(&ctx->sess, max_key_size,
					   TEE_TYPE_DSA_PUBLIC_KEY, key_attrs,
					   num_key_attrs, &obh2))
				return false;

			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_DSA_PRIVATE_VALUE,
				       tv->params.dsa.priv_val,
				       tv->params.dsa.priv_val_len);

			if (!create_key(&ctx->sess, max_key_size,
					   TEE_TYPE_DSA_KEYPAIR, key_attrs,
					   num_key_attrs, &obh1))
				return false;
			break;

		case TEE_MAIN_ALGO_ECDSA:
			switch (tv->algo) {
			case TEE_ALG_ECDSA_P192:
				curve = TEE_ECC_CURVE_NIST_P192;
				break;
			case TEE_ALG_ECDSA_P224:
				curve = TEE_ECC_CURVE_NIST_P224;
				break;
			case TEE_ALG_ECDSA_P256:
				curve = TEE_ECC_CURVE_NIST_P256;
				break;
			case TEE_ALG_ECDSA_P384:
				curve = TEE_ECC_CURVE_NIST_P384;
				break;
			case TEE_ALG_ECDSA_P521:
				curve = TEE_ECC_CURVE_NIST_P521;
				break;
			default:
				curve = 0xFF;
				break;
			}

			if (tv->algo == TEE_ALG_ECDSA_P521)
				max_key_size = 521;
			else
				max_key_size = tv->params.ecdsa.private_len * 8;

			tee_add_attr_value(&num_key_attrs, key_attrs,
					     TEE_ATTR_ECC_CURVE, curve, 0);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_ECC_PUBLIC_VALUE_X,
				       tv->params.ecdsa.public_x,
				       tv->params.ecdsa.public_x_len);
			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_ECC_PUBLIC_VALUE_Y,
				       tv->params.ecdsa.public_y,
				       tv->params.ecdsa.public_y_len);

			if (!create_key(&ctx->sess, max_key_size,
					   TEE_TYPE_ECDSA_PUBLIC_KEY, key_attrs,
					   num_key_attrs, &obh2))
				return false;

			tee_add_attr(&num_key_attrs, key_attrs,
				       TEE_ATTR_ECC_PRIVATE_VALUE,
				       tv->params.ecdsa.private,
				       tv->params.ecdsa.private_len);

			if (!create_key(&ctx->sess, max_key_size,
					   TEE_TYPE_ECDSA_KEYPAIR, key_attrs,
					   num_key_attrs, &obh1))
				return false;
			break;

		default:
			return false;
		}

		out_size = sizeof(out);
		memset(out, 0, sizeof(out));
		switch (tv->mode) {
		case TEE_MODE_ENCRYPT:
			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, tv->algo, TEE_MODE_ENCRYPT,
					max_key_size);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_set_operation_key(&ctx->sess, op,
					obh2);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_free_transient_object(&ctx->sess,
					obh2);
			if (res != TEEC_SUCCESS)
				return res;

			obh2 = TEE_HANDLE_NULL;

			out_enc_size = sizeof(out_enc);
			res = ta_crypt_cmd_asymmetric_encrypt(&ctx->sess, op,
					NULL, 0, tv->ptx, tv->ptx_len, out_enc,
					&out_enc_size);
			if (res != TEEC_SUCCESS)
				return res;

			/*
			 * A PS which is random is added when formatting the
			 * message internally of the algorithm so we can't
			 * verify against precomputed values, instead we use the
			 * decrypt operation to see that output is correct.
			 */

			res = ta_crypt_cmd_free_operation(&ctx->sess, op);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, tv->algo, TEE_MODE_DECRYPT,
					max_key_size);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_set_operation_key(&ctx->sess, op,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_free_transient_object(&ctx->sess,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			obh1 = TEE_HANDLE_NULL;

			res = ta_crypt_cmd_asymmetric_decrypt(&ctx->sess, op,
					NULL, 0, out_enc, out_enc_size, out,
					&out_size);
			if (res != TEEC_SUCCESS)
				return res;

			//(void)ADBG_EXPECT_BUFFER(c, tv->ptx, tv->ptx_len, out,
			//			 out_size);
			break;

		case TEE_MODE_DECRYPT:
			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, tv->algo, TEE_MODE_DECRYPT,
					max_key_size);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_set_operation_key(&ctx->sess, op,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_free_transient_object(&ctx->sess,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			obh1 = TEE_HANDLE_NULL;

			res = ta_crypt_cmd_asymmetric_decrypt(&ctx->sess, op,
					NULL, 0, tv->ctx, tv->ctx_len, out,
					&out_size);
			if (res != TEEC_SUCCESS)
				return res;

			//(void)ADBG_EXPECT_BUFFER(c, tv->ptx, tv->ptx_len, out,
			//			 out_size);
			break;

		case TEE_MODE_SIGN:
			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, tv->algo, TEE_MODE_SIGN,
					max_key_size);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_set_operation_key(&ctx->sess, op,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_free_transient_object(&ctx->sess,
					obh1);
			if (res != TEEC_SUCCESS)
				return res;

			obh1 = TEE_HANDLE_NULL;

			res = ta_crypt_cmd_asymmetric_sign(&ctx->sess, op,
					algo_params, num_algo_params, ptx_hash,
					ptx_hash_size, out, &out_size);
			if (res != TEEC_SUCCESS)
				return res;

			if (TEE_ALG_GET_CHAIN_MODE(tv->algo) ==
			    TEE_CHAIN_MODE_PKCS1_PSS_MGF1 ||
			    tv->algo == TEE_ALG_DSA_SHA1 ||
			    tv->algo == TEE_ALG_DSA_SHA224 ||
			    tv->algo == TEE_ALG_DSA_SHA256 ||
			    TEE_ALG_GET_MAIN_ALG(tv->algo) ==
					    TEE_MAIN_ALGO_ECDSA) {
				res = ta_crypt_cmd_free_operation(&ctx->sess, op);
				if (res != TEEC_SUCCESS)
					return res;

				/*
				 * The salt or K is random so we can't verify
				 * signing against precomputed values, instead
				 * we use the verify operation to see that
				 * output is correct.
				 */
				res = ta_crypt_cmd_allocate_operation(&ctx->sess,
						&op, tv->algo,
						TEE_MODE_VERIFY, max_key_size);
				if (res != TEEC_SUCCESS)
					return res;

				res = ta_crypt_cmd_set_operation_key(&ctx->sess,
						op, obh2);
				if (res != TEEC_SUCCESS)
					return res;

				res = ta_crypt_cmd_free_transient_object(&ctx->sess,
						obh2);
				if (res != TEEC_SUCCESS)
					return res;

				obh2 = TEE_HANDLE_NULL;

				res = ta_crypt_cmd_asymmetric_verify(&ctx->sess,
						op, algo_params,
						num_algo_params, ptx_hash,
						ptx_hash_size, out, out_size);
				if (res != TEEC_SUCCESS)
					return res;
			}/* else {
				(void)ADBG_EXPECT_BUFFER(c, tv->ctx,
							 tv->ctx_len, out,
							 out_size);
			}*/
			break;

		case TEE_MODE_VERIFY:
			res = ta_crypt_cmd_allocate_operation(&ctx->sess,
					&op, tv->algo, TEE_MODE_VERIFY,
					max_key_size);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_set_operation_key(&ctx->sess, op,
					obh2);
			if (res != TEEC_SUCCESS)
				return res;

			res = ta_crypt_cmd_free_transient_object(&ctx->sess,
					obh2);
			if (res != TEEC_SUCCESS)
				return res;

			obh2 = TEE_HANDLE_NULL;

			res = ta_crypt_cmd_asymmetric_verify(&ctx->sess, op,
					algo_params, num_algo_params, ptx_hash,
					ptx_hash_size, tv->ctx, tv->ctx_len);
			if (res != TEEC_SUCCESS)
				return res;
			break;

		default:
			break;
		}

		res = ta_crypt_cmd_free_operation(&ctx->sess, op);
		if (res != TEEC_SUCCESS)
			return res;

		res = ta_crypt_cmd_free_transient_object(&ctx->sess,
				obh2);
		if (res != TEEC_SUCCESS)
			return res;

		obh2 = TEE_HANDLE_NULL;

		res = ta_crypt_cmd_free_transient_object(&ctx->sess,
				obh1);
		if (res != TEEC_SUCCESS)
			return res;

		obh1 = TEE_HANDLE_NULL;
	}
}

int main(int argc, char *argv[])
{
	struct ca_ctx ctx;
	TEEC_Result res;

	printf("Prepare session with the TA\n");
	bsw_csm_teec_open_session(&ctx);

	printf("Test TEE Internal API Asymmetric Cipher operations\n");
	res = test_bsw_csm_asymmetric_cipher(&ctx);
	if (res != TEEC_SUCCESS)
		errx(1, "Asymmetric Cipher failed with code 0x%x", res);

	bsw_csm_teec_close_session(&ctx);

	return 0;
}
